export interface Translation {
  title: string;
  subtitle: string;
  galleryDescription: string;
  viewInGallery: string;
  browseGallery: string;
  whatIs: string;
  whatIsContent: string;
  statistics: string;
  totalPrompts: string;
  featuredPrompts: string;
  lastUpdated: string;
  featuredSection: string;
  allPrompts: string;
  morePrompts: string;
  morePromptsContent: string;
  prompt: string;
  tips: string;
  tipsSection: string;
  author: string;
  source: string;
  published: string;
  featured: string;
  tryItNow: string;
  contributing: string;
  contributingContent: string;
  license: string;
  licenseContent: string;
  acknowledgements: string;
  acknowledgementsContent: string;
  starHistory: string;
  madeWith: string;
  copyright: string;
  videoPreview: string;
  referenceImage: string;
  tableOfContents: string;
  copyrightNotice: string;
  // Comparison table
  featureCol: string;
  githubReadmeCol: string;
  galleryCol: string;
  videoPlayback: string;
  staticThumbnails: string;
  fullVideoPlayback: string;
  searchFeature: string;
  ctrlFOnly: string;
  fuzzySearch: string;
  mobileFeature: string;
  mobileBasic: string;
  mobileResponsive: string;
  languagesFeature: string;
  // Stats table
  metricCol: string;
  countCol: string;
  tipsAndTutorials: string;
  // Prompt list
  sortedByDate: string;
  moreNotShown: string;
  // Tips section
  tipsSubtitle: string;
  andMoreTips: string;
  viewAllInGallery: string;
  // Video
  clickToWatch: string;
  watchVideo: string;
  // Footer
  submitPrompt: string;
  starRepo: string;
  autoGenerated: string;
  // Renoise traffic CTAs
  runItCta: string;
  runItCtaLink: string;
  exploreMore: string;
  featureSeedance: string;
  guideMovieTrailer: string;
  guideMusicVideo: string;
  guidePhotoToVideo: string;
}

const en: Translation = {
  title: 'Awesome Seedance 2.0 Video Prompts',
  subtitle: 'A curated collection of high-quality video generation prompts for ByteDance\'s Seedance 2.0',
  galleryDescription: 'Browse all prompts with video previews, search, and one-click generation',
  viewInGallery: 'View in Web Gallery',
  browseGallery: 'Browse all Seedance 2.0 prompts on Renoise',
  whatIs: 'What is Seedance 2.0?',
  whatIsContent: `**Seedance 2.0** is a video generation model developed by **ByteDance**. It is the industry's first model supporting **simultaneous quad-modal input** — image, video, audio, and text.

**Key Features:**

* 🎥 **Text-to-Video** — Generate videos from text descriptions
* 🖼️ **Image-to-Video** — Animate static images into dynamic videos
* 📹 **Video-to-Video** — Transform and extend existing videos
* 🎵 **Audio-Driven** — Generate videos driven by audio input
* 📐 **Up to 1080p resolution**, 4–15 seconds duration
* 🔊 **Auto dubbing & scoring** — Automatic voiceover and background music`,
  statistics: '📊 Statistics',
  totalPrompts: 'Total Prompts',
  featuredPrompts: 'Featured',
  lastUpdated: 'Last Updated',
  featuredSection: '⭐ Featured Prompts',
  allPrompts: '🎬 All Prompts',
  morePrompts: '📚 More Prompts',
  morePromptsContent: 'This README shows the latest prompts. Visit our gallery for the full collection with video previews and search.',
  prompt: 'Prompt',
  tips: 'Tips',
  tipsSection: '💡 Usage Tips',
  author: 'Author',
  source: 'Source',
  published: 'Published',
  featured: '⭐ Featured',
  tryItNow: '👉 Try it now →',
  contributing: '🤝 Contributing',
  contributingContent: 'We welcome contributions! Please see our [Contributing Guide](CONTRIBUTING.md) for details on how to submit prompts.',
  license: '📄 License',
  licenseContent: 'This collection is licensed under [CC BY 4.0](LICENSE). You are free to share and adapt the prompts with attribution.',
  acknowledgements: '🙏 Acknowledgements',
  acknowledgementsContent: 'Thanks to all the creators who shared their prompts with the community.',
  starHistory: '⭐ Star History',
  madeWith: 'Made with ❤️ by',
  copyright: '© 2026 Renoise. All rights reserved.',
  videoPreview: 'Video Preview',
  referenceImage: 'Reference Image',
  tableOfContents: 'Table of Contents',
  copyrightNotice: 'Copyright Notice: All prompts are collected from the community for educational purposes. If you believe any content infringes on your rights, please open an issue and we will remove it promptly.',
  featureCol: 'Feature',
  githubReadmeCol: 'GitHub README',
  galleryCol: 'Gallery',
  videoPlayback: 'Video Playback',
  staticThumbnails: 'Static thumbnails',
  fullVideoPlayback: 'Full video playback',
  searchFeature: 'Search',
  ctrlFOnly: 'Ctrl+F only',
  fuzzySearch: 'Multi-field fuzzy search',
  mobileFeature: 'Mobile',
  mobileBasic: 'Basic',
  mobileResponsive: 'Fully responsive',
  languagesFeature: 'Languages',
  metricCol: 'Metric',
  countCol: 'Count',
  tipsAndTutorials: 'Tips & Tutorials',
  sortedByDate: 'Sorted by publish date (newest first)',
  moreNotShown: 'more prompts not shown here',
  tipsSubtitle: 'Community tutorials and tips for getting the most out of Seedance 2.0',
  andMoreTips: 'and {n} more tips.',
  viewAllInGallery: 'View all in Gallery',
  clickToWatch: 'Click image to watch video',
  watchVideo: 'Watch Video',
  submitPrompt: 'Submit a Prompt',
  starRepo: 'Star this repo',
  autoGenerated: 'This README is automatically generated. Last updated:',
  runItCta: '💡 **Copy any prompt and {link}** — no setup, no install.',
  runItCtaLink: 'run it instantly in Renoise →',
  exploreMore: '🚀 Explore more on Renoise',
  featureSeedance: 'Seedance 2.0 model',
  guideMovieTrailer: 'AI Movie Trailer',
  guideMusicVideo: 'AI Music Video',
  guidePhotoToVideo: 'AI Photo to Video',
};

const zhCN: Translation = {
  title: 'Awesome Seedance 2.0 视频提示词',
  subtitle: '精选 ByteDance Seedance 2.0 高质量视频生成提示词合集',
  galleryDescription: '浏览所有提示词，支持视频预览、搜索和一键生成',
  viewInGallery: '🎬 在画廊中查看',
  browseGallery: '浏览画廊',
  whatIs: 'Seedance 2.0 是什么？',
  whatIsContent: `**Seedance 2.0** 是 **字节跳动** 开发的视频生成模型，是业界首个支持 **图片、视频、音频、文本四模态同时输入** 的模型。

**核心特性：**

* 🎥 **文生视频** — 根据文字描述生成视频
* 🖼️ **图生视频** — 将静态图片动画化
* 📹 **视频转视频** — 变换和扩展现有视频
* 🎵 **音频驱动** — 通过音频输入驱动视频生成
* 📐 **最高 1080p 分辨率**，4–15 秒时长
* 🔊 **自动配音配乐** — 自动生成旁白和背景音乐`,
  statistics: '📊 统计数据',
  totalPrompts: '提示词总数',
  featuredPrompts: '精选',
  lastUpdated: '最后更新',
  featuredSection: '⭐ 精选提示词',
  allPrompts: '🎬 所有提示词',
  morePrompts: '📚 更多提示词',
  morePromptsContent: '本 README 展示了最新的提示词。访问我们的画廊查看完整合集，支持视频预览和搜索。',
  prompt: '提示词',
  tips: '使用技巧',
  tipsSection: '💡 使用技巧',
  author: '作者',
  source: '来源',
  published: '发布日期',
  featured: '⭐ 精选',
  tryItNow: '👉 立即试用 →',
  contributing: '🤝 贡献指南',
  contributingContent: '欢迎贡献！请查看我们的[贡献指南](CONTRIBUTING.md)了解如何提交提示词。',
  license: '📄 许可证',
  licenseContent: '本合集采用 [CC BY 4.0](LICENSE) 许可。你可以在注明出处的情况下自由分享和改编这些提示词。',
  acknowledgements: '🙏 致谢',
  acknowledgementsContent: '感谢所有与社区分享提示词的创作者们。',
  starHistory: '⭐ Star 历史',
  madeWith: '用 ❤️ 制作',
  copyright: '© 2026 Renoise 版权所有',
  videoPreview: '视频预览',
  referenceImage: '参考图片',
  tableOfContents: '目录',
  copyrightNotice: '版权声明：所有提示词均来自社区，仅用于学习目的。如果您认为任何内容侵犯了您的权利，请提交 Issue，我们将及时删除。',
  featureCol: '功能',
  githubReadmeCol: 'GitHub README',
  galleryCol: '在线画廊',
  videoPlayback: '视频播放',
  staticThumbnails: '静态缩略图',
  fullVideoPlayback: '完整视频播放',
  searchFeature: '搜索',
  ctrlFOnly: '仅 Ctrl+F',
  fuzzySearch: '多字段模糊搜索',
  mobileFeature: '移动端',
  mobileBasic: '基础',
  mobileResponsive: '完全响应式',
  languagesFeature: '多语言',
  metricCol: '指标',
  countCol: '数量',
  tipsAndTutorials: '技巧 & 教程',
  sortedByDate: '按发布日期排序（最新优先）',
  moreNotShown: '条提示词未在此显示',
  tipsSubtitle: '社区分享的 Seedance 2.0 使用技巧和教程',
  andMoreTips: '以及另外 {n} 条技巧。',
  viewAllInGallery: '在画廊中查看全部',
  clickToWatch: '点击图片观看视频',
  watchVideo: '观看视频',
  submitPrompt: '提交提示词',
  starRepo: '点个 Star',
  autoGenerated: '本 README 由脚本自动生成。最后更新：',
  runItCta: '💡 **复制任意提示词，{link}** — 无需安装、无需配置。',
  runItCtaLink: '在 Renoise 里一键生成 →',
  exploreMore: '🚀 在 Renoise 探索更多',
  featureSeedance: 'Seedance 2.0 模型',
  guideMovieTrailer: 'AI 电影预告片',
  guideMusicVideo: 'AI 音乐视频',
  guidePhotoToVideo: 'AI 图片转视频',
};

const ja: Translation = {
  title: 'Awesome Seedance 2.0 動画プロンプト',
  subtitle: 'Seedance 2.0 の厳選ビデオ生成プロンプト集',
  galleryDescription: 'すべてのプロンプトを動画プレビュー・検索・ワンクリック生成で閲覧',
  viewInGallery: '🎬 ウェブギャラリーで閲覧',
  browseGallery: 'Renoise でプロンプトを閲覧',
  whatIs: 'Seedance 2.0 とは？',
  whatIsContent: `**Seedance 2.0** は **ByteDance** が開発した動画生成モデルで、業界初の **画像・動画・音声・テキストの4モーダル同時入力** に対応しています。

**主な特徴：**

* 🎥 **テキストから動画** — テキスト記述から動画を生成
* 🖼️ **画像から動画** — 静止画をアニメーション化
* 📹 **動画変換** — 既存動画の変換・拡張
* 🎵 **音声駆動** — 音声入力による動画生成
* 📐 **最大1080p解像度**、4〜15秒
* 🔊 **自動吹替・BGM** — 自動ナレーション・BGM生成`,
  statistics: '📊 統計',
  totalPrompts: 'プロンプト総数',
  featuredPrompts: '注目',
  lastUpdated: '最終更新',
  featuredSection: '⭐ 注目プロンプト',
  allPrompts: '🎬 全プロンプト',
  morePrompts: '📚 さらに多くのプロンプト',
  morePromptsContent: 'この README には最新のプロンプトを掲載しています。動画プレビューと検索付きの完全なコレクションはギャラリーをご覧ください。',
  prompt: 'プロンプト',
  tips: '使い方のコツ',
  tipsSection: '💡 使い方のコツ',
  author: '作者',
  source: 'ソース',
  published: '公開日',
  featured: '⭐ 注目',
  tryItNow: '👉 今すぐ試す →',
  contributing: '🤝 コントリビュート',
  contributingContent: 'コントリビュートを歓迎します！プロンプトの提出方法は[コントリビュートガイド](CONTRIBUTING.md)をご覧ください。',
  license: '📄 ライセンス',
  licenseContent: 'このコレクションは [CC BY 4.0](LICENSE) ライセンスの下で公開されています。帰属表示のもと、自由に共有・改変できます。',
  acknowledgements: '🙏 謝辞',
  acknowledgementsContent: 'コミュニティでプロンプトを共有してくださったすべてのクリエイターに感謝します。',
  starHistory: '⭐ Star 履歴',
  madeWith: '❤️ で制作',
  copyright: '© 2026 Renoise. All rights reserved.',
  videoPreview: '動画プレビュー',
  referenceImage: '参考画像',
  tableOfContents: '目次',
  copyrightNotice: '著作権に関するお知らせ：すべてのプロンプトは教育目的でコミュニティから収集されています。権利侵害に該当するコンテンツがある場合は、Issue を作成してください。速やかに対応いたします。',
  featureCol: '機能',
  githubReadmeCol: 'GitHub README',
  galleryCol: 'ギャラリー',
  videoPlayback: '動画再生',
  staticThumbnails: '静止サムネイル',
  fullVideoPlayback: '完全な動画再生',
  searchFeature: '検索',
  ctrlFOnly: 'Ctrl+F のみ',
  fuzzySearch: '複数フィールドのあいまい検索',
  mobileFeature: 'モバイル',
  mobileBasic: '基本対応',
  mobileResponsive: '完全レスポンシブ',
  languagesFeature: '言語',
  metricCol: '指標',
  countCol: '数',
  tipsAndTutorials: 'ヒント & チュートリアル',
  sortedByDate: '公開日順（新しい順）',
  moreNotShown: '件のプロンプトが非表示',
  tipsSubtitle: 'Seedance 2.0 を最大限に活用するためのコミュニティのヒントとチュートリアル',
  andMoreTips: 'その他 {n} 件のヒント。',
  viewAllInGallery: 'ギャラリーですべて表示',
  clickToWatch: '画像をクリックして動画を再生',
  watchVideo: '動画を見る',
  submitPrompt: 'プロンプトを提出',
  starRepo: 'Star する',
  autoGenerated: 'この README は自動生成されています。最終更新：',
  runItCta: '💡 **プロンプトをコピーして{link}** — セットアップ・インストール不要。',
  runItCtaLink: 'Renoise ですぐに生成 →',
  exploreMore: '🚀 Renoise でもっと見る',
  featureSeedance: 'Seedance 2.0 モデル',
  guideMovieTrailer: 'AI 映画予告編',
  guideMusicVideo: 'AI ミュージックビデオ',
  guidePhotoToVideo: 'AI 写真から動画',
};

const ptBR: Translation = {
  title: 'Awesome Seedance 2.0 Prompts de Vídeo',
  subtitle: 'Coleção curada de prompts de geração de vídeo para o Seedance 2.0 da ByteDance',
  galleryDescription: 'Navegue por todos os prompts com prévias de vídeo, busca e geração com um clique',
  viewInGallery: '🎬 Ver na Galeria Web',
  browseGallery: 'Ver todos os prompts Seedance 2.0 no Renoise',
  whatIs: 'O que é o Seedance 2.0?',
  whatIsContent: `**Seedance 2.0** é um modelo de geração de vídeo desenvolvido pela **ByteDance**. É o primeiro modelo do setor que suporta **entrada simultânea de quatro modalidades** — imagem, vídeo, áudio e texto.

**Principais Recursos:**

* 🎥 **Texto para Vídeo** — Gere vídeos a partir de descrições textuais
* 🖼️ **Imagem para Vídeo** — Anime imagens estáticas em vídeos dinâmicos
* 📹 **Vídeo para Vídeo** — Transforme e estenda vídeos existentes
* 🎵 **Áudio como Base** — Gere vídeos a partir de entrada de áudio
* 📐 **Resolução até 1080p**, duração de 4–15 segundos
* 🔊 **Dublagem e trilha automáticas** — Narração e música de fundo automáticas`,
  statistics: '📊 Estatísticas',
  totalPrompts: 'Total de Prompts',
  featuredPrompts: 'Destaques',
  lastUpdated: 'Última Atualização',
  featuredSection: '⭐ Prompts em Destaque',
  allPrompts: '🎬 Todos os Prompts',
  morePrompts: '📚 Mais Prompts',
  morePromptsContent: 'Este README mostra os prompts mais recentes. Visite nossa galeria para a coleção completa com prévias de vídeo e busca.',
  prompt: 'Prompt',
  tips: 'Dicas',
  tipsSection: '💡 Dicas de Uso',
  author: 'Autor',
  source: 'Fonte',
  published: 'Publicado',
  featured: '⭐ Destaque',
  tryItNow: '👉 Experimente agora →',
  contributing: '🤝 Contribuições',
  contributingContent: 'Contribuições são bem-vindas! Consulte nosso [Guia de Contribuição](CONTRIBUTING.md) para saber como enviar prompts.',
  license: '📄 Licença',
  licenseContent: 'Esta coleção é licenciada sob [CC BY 4.0](LICENSE). Você pode compartilhar e adaptar os prompts livremente com atribuição.',
  acknowledgements: '🙏 Agradecimentos',
  acknowledgementsContent: 'Agradecemos a todos os criadores que compartilharam seus prompts com a comunidade.',
  starHistory: '⭐ Histórico de Stars',
  madeWith: 'Feito com ❤️ por',
  copyright: '© 2026 Renoise. Todos os direitos reservados.',
  videoPreview: 'Prévia do Vídeo',
  referenceImage: 'Imagem de Referência',
  tableOfContents: 'Índice',
  copyrightNotice: 'Aviso de Direitos Autorais: Todos os prompts foram coletados da comunidade para fins educacionais. Se você acredita que algum conteúdo infringe seus direitos, abra uma issue e removeremos prontamente.',
  featureCol: 'Recurso',
  githubReadmeCol: 'GitHub README',
  galleryCol: 'Galeria',
  videoPlayback: 'Reprodução de Vídeo',
  staticThumbnails: 'Miniaturas estáticas',
  fullVideoPlayback: 'Reprodução completa de vídeo',
  searchFeature: 'Busca',
  ctrlFOnly: 'Apenas Ctrl+F',
  fuzzySearch: 'Busca fuzzy multicampo',
  mobileFeature: 'Mobile',
  mobileBasic: 'Básico',
  mobileResponsive: 'Totalmente responsivo',
  languagesFeature: 'Idiomas',
  metricCol: 'Métrica',
  countCol: 'Quantidade',
  tipsAndTutorials: 'Dicas & Tutoriais',
  sortedByDate: 'Ordenado por data de publicação (mais recente primeiro)',
  moreNotShown: 'prompts adicionais não exibidos aqui',
  tipsSubtitle: 'Tutoriais e dicas da comunidade para aproveitar ao máximo o Seedance 2.0',
  andMoreTips: 'e mais {n} dicas.',
  viewAllInGallery: 'Ver tudo na Galeria',
  clickToWatch: 'Clique na imagem para assistir o vídeo',
  watchVideo: 'Assistir Vídeo',
  submitPrompt: 'Enviar um Prompt',
  starRepo: 'Dar Star',
  autoGenerated: 'Este README é gerado automaticamente. Última atualização:',
  runItCta: '💡 **Copie qualquer prompt e {link}** — sem instalação, sem configuração.',
  runItCtaLink: 'gere na hora no Renoise →',
  exploreMore: '🚀 Explore mais no Renoise',
  featureSeedance: 'modelo Seedance 2.0',
  guideMovieTrailer: 'Trailer de Filme com IA',
  guideMusicVideo: 'Videoclipe com IA',
  guidePhotoToVideo: 'Foto para Vídeo com IA',
};

const es: Translation = {
  title: 'Awesome Seedance 2.0 Prompts de Video',
  subtitle: 'Colección curada de prompts de generación de video para el Seedance 2.0 de ByteDance',
  galleryDescription: 'Explora todos los prompts con vistas previas de video, búsqueda y generación con un clic',
  viewInGallery: '🎬 Ver en la Galería Web',
  browseGallery: 'Ver todos los prompts Seedance 2.0 en Renoise',
  whatIs: '¿Qué es Seedance 2.0?',
  whatIsContent: `**Seedance 2.0** es un modelo de generación de video desarrollado por **ByteDance**. Es el primer modelo de la industria que soporta **entrada simultánea de cuatro modalidades** — imagen, video, audio y texto.

**Características Principales:**

* 🎥 **Texto a Video** — Genera videos a partir de descripciones textuales
* 🖼️ **Imagen a Video** — Anima imágenes estáticas en videos dinámicos
* 📹 **Video a Video** — Transforma y extiende videos existentes
* 🎵 **Audio como Base** — Genera videos a partir de entrada de audio
* 📐 **Resolución hasta 1080p**, duración de 4–15 segundos
* 🔊 **Doblaje y música automáticos** — Narración y música de fondo automáticas`,
  statistics: '📊 Estadísticas',
  totalPrompts: 'Total de Prompts',
  featuredPrompts: 'Destacados',
  lastUpdated: 'Última Actualización',
  featuredSection: '⭐ Prompts Destacados',
  allPrompts: '🎬 Todos los Prompts',
  morePrompts: '📚 Más Prompts',
  morePromptsContent: 'Este README muestra los prompts más recientes. Visita nuestra galería para la colección completa con vistas previas de video y búsqueda.',
  prompt: 'Prompt',
  tips: 'Consejos',
  tipsSection: '💡 Consejos de Uso',
  author: 'Autor',
  source: 'Fuente',
  published: 'Publicado',
  featured: '⭐ Destacado',
  tryItNow: '👉 Pruébalo ahora →',
  contributing: '🤝 Contribuciones',
  contributingContent: '¡Las contribuciones son bienvenidas! Consulta nuestra [Guía de Contribución](CONTRIBUTING.md) para saber cómo enviar prompts.',
  license: '📄 Licencia',
  licenseContent: 'Esta colección está licenciada bajo [CC BY 4.0](LICENSE). Puedes compartir y adaptar los prompts libremente con atribución.',
  acknowledgements: '🙏 Agradecimientos',
  acknowledgementsContent: 'Gracias a todos los creadores que compartieron sus prompts con la comunidad.',
  starHistory: '⭐ Historial de Stars',
  madeWith: 'Hecho con ❤️ por',
  copyright: '© 2026 Renoise. Todos los derechos reservados.',
  videoPreview: 'Vista Previa del Video',
  referenceImage: 'Imagen de Referencia',
  tableOfContents: 'Índice',
  copyrightNotice: 'Aviso de Derechos de Autor: Todos los prompts fueron recopilados de la comunidad con fines educativos. Si cree que algún contenido infringe sus derechos, abra un issue y lo eliminaremos de inmediato.',
  featureCol: 'Característica',
  githubReadmeCol: 'GitHub README',
  galleryCol: 'Galería',
  videoPlayback: 'Reproducción de Video',
  staticThumbnails: 'Miniaturas estáticas',
  fullVideoPlayback: 'Reproducción completa de video',
  searchFeature: 'Búsqueda',
  ctrlFOnly: 'Solo Ctrl+F',
  fuzzySearch: 'Búsqueda difusa multicampo',
  mobileFeature: 'Móvil',
  mobileBasic: 'Básico',
  mobileResponsive: 'Totalmente responsivo',
  languagesFeature: 'Idiomas',
  metricCol: 'Métrica',
  countCol: 'Cantidad',
  tipsAndTutorials: 'Consejos & Tutoriales',
  sortedByDate: 'Ordenado por fecha de publicación (más reciente primero)',
  moreNotShown: 'prompts adicionales no mostrados aquí',
  tipsSubtitle: 'Tutoriales y consejos de la comunidad para sacar el máximo provecho de Seedance 2.0',
  andMoreTips: 'y {n} consejos más.',
  viewAllInGallery: 'Ver todo en la Galería',
  clickToWatch: 'Haz clic en la imagen para ver el video',
  watchVideo: 'Ver Video',
  submitPrompt: 'Enviar un Prompt',
  starRepo: 'Dar Star',
  autoGenerated: 'Este README se genera automáticamente. Última actualización:',
  runItCta: '💡 **Copia cualquier prompt y {link}** — sin instalación ni configuración.',
  runItCtaLink: 'genéralo al instante en Renoise →',
  exploreMore: '🚀 Explora más en Renoise',
  featureSeedance: 'modelo Seedance 2.0',
  guideMovieTrailer: 'Tráiler de Película con IA',
  guideMusicVideo: 'Videoclip con IA',
  guidePhotoToVideo: 'Foto a Video con IA',
};

const I18N: Record<string, Translation> = {
  'en': en,
  'zh-CN': zhCN,
  'ja': ja,
  'pt-BR': ptBR,
  'es': es,
};

export function t(key: keyof Translation, locale: string): string {
  const lang = I18N[locale] || I18N['en'];
  return lang[key] || en[key] || key;
}

const DATE_LOCALES: Record<string, string> = {
  'en': 'en-US',
  'zh-CN': 'zh-CN',
  'ja': 'ja-JP',
  'pt-BR': 'pt-BR',
  'es': 'es-ES',
};

export function formatDateLocalized(iso: string | undefined, locale: string): string {
  if (!iso) return 'N/A';
  const dateLocale = DATE_LOCALES[locale] || 'en-US';
  return new Date(iso).toLocaleDateString(dateLocale, {
    year: 'numeric', month: 'short', day: 'numeric',
  });
}
